[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.format]
# опционально; можно убрать весь блок, если используешь Black
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
# правила теперь лежат в блоке lint.*
select = ["E", "F", "I", "B", "UP", "C4"]
ignore = ["E203", "E501"]

[tool.ruff.lint.isort]
known-first-party = ["tgbot"]
combine-as-imports = true
force-single-line = false
