"""create questions and answers tables

Revision ID: 046cebe54d7a
Revises: 6d561348812d
Create Date: 2025-09-22 21:05:10.636648

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "046cebe54d7a"
down_revision: str | Sequence[str] | None = "6d561348812d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
