"""create questions and answers tables

Revision ID: 5579c91725da
Revises:
Create Date: 2025-09-22 20:45:36.860877

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5579c91725da"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
