"""create questions and answers tables

Revision ID: 9d57d2594508
Revises: 046cebe54d7a
Create Date: 2025-09-22 21:05:23.050236

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9d57d2594508"
down_revision: str | Sequence[str] | None = "046cebe54d7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
